name: CI/CD Docker

# 워크플로를 자동으로 트리거 하기 위함
on: 
  push: 
    branches: [ master ]
env: 
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/node
  VERSION: ${{ github.sha }}
  NAME: node_cicd
jobs:
  # job_id 
  build:
    # github에 표시되는 작업의 이름
    name: Build
    # 어디서 실행할건지
    runs-on: ubuntu-latest 
    steps:
      # github에 표시할 단계의 이름
      - name: Check out source code
        # 실행할 작업을 선택
        uses: actions/checkout@v2
      - name: Set up docker buildx
        # 단계의 고유 식별자 ( steps_id )
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
  # job_id
  deploy:
    # 이 작업을 실행하기 전에 성공적으로 완료해야 하는 작업
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-node ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 3000:3000 --name node_cicd --restart always ${{ env.DOCKER_IMAGE }}:latest